apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: just-like-clockwork-backend-env
  namespace: just-like-clockwork-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: just-like-clockwork-backend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/just-like-clockwork-backend/just-like-clockwork-backend/env
