apiVersion: v1
kind: Service
metadata:
  name: just-like-clockwork-backend
spec:
  type: NodePort
  selector:
    app: just-like-clockwork-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32004
